{% set name = "python-kaleido" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/plotly/Kaleido/releases/download/v{{ version }}/kaleido-{{ version }}.tar.gz
  sha256: fdb673a9759835d4f455990fc1ff8919bd100a0d34f2d3de7bd5eeb2162b57ec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - kaleido-core ={{ version }}

test:
  requires:
    - plotly >=4.10
  imports:
    - kaleido

about:
  home: https://github.com/plotly/Kaleido
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Fast static image export for web-based visualization libraries
  description: |
    Python interface to Kaleido, a cross-platform library for generating static images
    (e.g. png, svg, pdf, etc.) for web-based visualization libraries, with a
    particular focus on eliminating external dependencies.
  doc_url: https://plotly.com/python/static-image-export/
  dev_url: https://github.com/plotly/Kaleido

extra:
  recipe-maintainers:
    - jonmmease
