{% set name = "python-kaleido" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/plotly/Kaleido/releases/download/v{{ version }}/kaleido-{{ version }}.tar.gz
  sha256: 502d8ba64737924efaf5e94c2736745bcc7c926e6cc535838be36c0fc06330bd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - kaleido-core ={{ version }}

test:
  requires:
    - plotly >=4.10
  imports:
    - kaleido

about:
  home: https://github.com/plotly/Kaleido
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Fast static image export for web-based visualization libraries
  description: |
    Python interface to Kaleido, a cross-platform library for generating static images
    (e.g. png, svg, pdf, etc.) for web-based visualization libraries, with a
    particular focus on eliminating external dependencies.
  doc_url: https://plotly.com/python/static-image-export/
  dev_url: https://github.com/plotly/Kaleido

extra:
  recipe-maintainers:
    - jonmmease
